# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{syslog_logger}
  s.version = "1.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.2") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hodel", "Chris Powell", "Matthew Boeh", "Kristjan Petursson"]
  s.date = %q{2009-12-03}
  s.email = ["drbrain@segment7.net", "cpowell@prylis.com", "mboeh@desperance.net", "kristjan@gmail.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "lib/analyzer_tools/syslog_logger.rb",
     "lib/syslog_logger.rb",
     "syslog_logger.gemspec",
     "test/test_syslog_logger.rb"
  ]
  s.homepage = %q{http://github.com/kristjan/sysloglogger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An improved Logger replacement that logs to syslog. It is almost drop-in with a few caveats.}
  s.test_files = [
    "test/test_syslog_logger.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

